### ISSUE TITLE
Leaf nodes should support fql

### ISSUE THREAD

**Issue by ersinakinci** [shiftx/faunadb-graphql-lib#3]
When `astToFaunaQuery` traverses a leaf node, it assigns a value based on `_item_`:

https://github.com/shiftx/faunadb-graphql-lib/blob/1c88f009a5368e70773729ccc39b9e1d63519d53/src/utilities/astToFaunaQuery.ts#L71-L81

It would be very helpful to support the `fql` param to support overriding the default value provided to the node. In fact, `GraphQLFaunaPageType` is currently broken because an FQL expressions are provided for the cursors but since these are interpreted as leaf nodes, the expressions are ignored: https://github.com/shiftx/faunadb-graphql-lib/blob/1c88f009a5368e70773729ccc39b9e1d63519d53/src/types/GraphQLFaunaPageType.ts#L10-L17

**Comment by eigilsagafos** [comment]
Thanks. As I mentioned this lib is not ready :) But feel free to draw inspiration from it. Hopefully I'll have time within the next few weeks to get the first "beta" version ready for feedback. I'll close the issues for now. Feel free to reach out to me on the Fauna Slack forum.
